// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CpuStatus } from "./CpuStatus";
import type { SystemEvent } from "./SystemEvent";

export interface CpuState { pc: number, regs: Array<number>, cycles: number, status: CpuStatus, csrs: Array<[number, number]>, mem: Array<[bigint, number]>, heapTop: number, outputBuffer: string, systemLog: Array<SystemEvent>, }