// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CpuState {
  pc: number;
  regs: Array<number>;
  cycles: number;
  status: string;
  csrs: Array<[number, number]>;
  mem: Array<[bigint, number]>;
  heapTop: number;
}
