// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CpuState } from "./CpuState";

export type EmulatorResponse =
  | { type: "state"; data: CpuState }
  | { type: "loaded"; state: CpuState; sourceMap: Array<[number, number]> }
  | { type: "error"; message: string };
