// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ExtensionInfo { code: string, name: string, summary: string, mandatory: boolean, enabled: boolean, }