// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperandDoc } from "./OperandDoc";

export interface FormatInfo { id: string, name: string, kind: string, syntax: string, operands: Array<OperandDoc>, blurb: string, }