// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface InstructionInfo { mnemonic: string, extension: string, format: string, operation: string, description: string, }