// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Notice = { "kind": "ProgramExitedNormally" } | { "kind": "ProgramExited", code: number, raw: number, } | { "kind": "BreakpointHit" } | { "kind": "Syscall", name: string, pc: number, bytes: number | null, count: number, };