// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegisterUse = { "dir": "in", reg: string, desc: string, } | { "dir": "out", reg: string, desc: string, };