// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegisterUse } from "./RegisterUse";

export interface SyscallInfo { name: string, code: number, registers: Array<RegisterUse>, description: string, }