// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmulatorError } from "./EmulatorError";
import type { Notice } from "./Notice";
import type { Severity } from "./Severity";

export interface SystemEvent { severity: Severity, fault: EmulatorError | null, notice: Notice | null, }